
drop table IAL_STOCK_LOCATION_TEMP;
commit;

 create table IAL_STOCK_LOCATION_TEMP as
 
 SELECT 
   PARTDES,PART_NO,PRODUCT_FAMILY,  
sum(BUS_BODY_QTY) BUS_BODY_QTY,                
sum(DEALER_PD_QTY) DEALER_PD_QTY,
sum(FAIR_DEMO_QTY) FAIR_DEMO_QTY,
sum(LC_QTY) LC_QTY,                 
sum(OUTSIDE_BWS_QTY) OUTSIDE_BWS_QTY,
sum(TOTAL_OT_QTY) TOTAL_OT_QTY,
sum(TRANSPORTT_QTY)TRANSPORTT_QTY,

  sum(Dhamrai_CKD#RFD_CKD) Dhamrai_CKD#RFD_CKD,
sum(Dhamrai_CBU#RFD_CBU) Dhamrai_CBU#RFD_CBU,
sum(Dhamrai_CKD#DO_ISSUED) Dhamrai_CKD#DO_ISSUED,
sum(Dhamrai_CKD#BOOKED_DAP) Dhamrai_CKD#BOOKED_DAP,
sum(Dhamrai_CKD#DEALER_POINT_DISPLAY) Dhamrai_CKD#DEALER_POINT_DISPLAY,
sum(Dhamrai_CKD#FAIR_AND_DEMO) Dhamrai_CKD#FAIR_AND_DEMO,
sum(Dhamrai_CKD#OUTSIDE_BODY_WORKSHOP) Dhamrai_CKD#OUTSIDE_BODY_WORKSHOP,
sum(Dhamrai_CKD#BUS_BODY) Dhamrai_CKD#BUS_BODY,
sum(Dhamrai_CBU#PDI_PTS) Dhamrai_CBU#PDI_PTS,
sum(Dhamrai_CKD#TOTAL_OT) Dhamrai_CKD#TOTAL_OT,
sum(Joydebpur#RFD) Joydebpur#RFD,
sum(Joydebpur#DO_ISSUED) Joydebpur#DO_ISSUED,
sum(Joydebpur#BOOKED) Joydebpur#BOOKED,
sum(Joydebpur#TOTAL_OT) Joydebpur#TOTAL_OT,
sum(Joydebpur#FAIR_AND_DEMO) Joydebpur#FAIR_AND_DEMO,
sum(Joydebpur#PDI_PTS) Joydebpur#PDI_PTS,
sum(Joydebpur#DEALER_POINT_DISPLAY) Joydebpur#DEALER_POINT_DISPLAY,
sum(Joydebpur#OUTSIDE_BODY_WORKSHOP) Joydebpur#OUTSIDE_BODY_WORKSHOP,
sum(Cumilla#RFD) Cumilla#RFD,
sum(Cumilla#DO_ISSUED) Cumilla#DO_ISSUED,
sum(Cumilla#BOOKED) Cumilla#BOOKED,
sum(Cumilla#FAIR_AND_DEMO) Cumilla#FAIR_AND_DEMO,
sum(Bogra#DEALER_POINT_DISPLAY) Bogra#DEALER_POINT_DISPLAY,
sum(Cumilla#OUTSIDE_BODY_WORKSHOP) Cumilla#OUTSIDE_BODY_WORKSHOP,
sum(Cumilla#PDI_PTS) Cumilla#PDI_PTS,
sum(Cumilla#OUTSIDE_SERVICE_CENTER) Cumilla#OUTSIDE_SERVICE_CENTER,
sum(Chattogram#RFD) CTG#RFD,
sum(Chattogram#DO_ISSUED) CTG#DO_ISSUED,
sum(Chattogram#BOOKED) CTG#BOOKED,
sum(Chattogram#FAIR_AND_DEMO) CTG#FAIR_AND_DEMO,
sum(Chattogram#PDI_PTS) CTG#PDI_PTS,
sum(Chattogram#DEALER_POINT_DISPLAY) CTG#DEALER_POINT_DISPLAY,
sum(Chattogram#TOTAL_OT) CTG#TOTAL_OT,
sum(Jashore#RFD) Jashore#RFD,
sum(Jashore#DO_ISSUED) Jashore#DO_ISSUED,
sum(Jashore#BOOKED) Jashore#BOOKED,
sum(Jashore#PDI_PTS) Jashore#PDI_PTS,
sum(Jashore#FAIR_AND_DEMO) Jashore#FAIR_AND_DEMO,
sum(Jashore#DEALER_POINT_DISPLAY) Jashore#DEALER_POINT_DISPLAY,
sum(Jashore#OUTSIDE_BODY_WORKSHOP) Jashore#OUTSIDE_BODY_WORKSHOP,
sum(Jashore#TOTAL_OT) Jashore#TOTAL_OT,
sum(Bogra#RFD) Bogra#RFD,
sum(Bogra#DO_ISSUED) Bogra#DO_ISSUED,
sum(Bogra#BOOKED) Bogra#BOOKED,
sum(Bogra#FAIR_AND_DEMO) Bogra#FAIR_AND_DEMO,
sum(Bogra#OUTSIDE_BODY_WORKSHOP) Bogra#OUTSIDE_BODY_WORKSHOP,
sum(Bogra#PDI_PTS) Bogra#PDI_PTS,
sum(Bogra#TOTAL_OT) Bogra#TOTAL_OT,
sum(Dhamrai_CKD#PDI_PTS) Dhamrai_CKD#PDI_PTS,
sum(Dhamrai_CBU#DO_ISSUED) Dhamrai_CBU#DO_ISSUED,
sum(Dhamrai_CBU#BOOKED_DAP) Dhamrai_CBU#BOOKED_DAP

    FROM (SELECT BUS_BODY_QTY,
                 CONTRACT,
                 DEALER_PD_QTY,
                 FAIR_DEMO_QTY,
                 LC_QTY,
                 LOCATION_DES,
                 OUTSIDE_BWS_QTY,
                 PARTDES,
                 PART_NO,
                 PRODUCT_FAMILY,
                 SITE_STOCK_LOCATION,
                 STK_QTY,
                 STOCK_LOCATION,
                 TOTAL_OT_QTY,
                 TRANSPORTT_QTY
             
            FROM REPORTDB.IAL_STOCK_REPORT_V) PIVOT (SUM (STK_QTY)
                                              FOR SITE_STOCK_LOCATION
                                              IN  (
'Dhamrai_CKD#RFD_CKD' Dhamrai_CKD#RFD_CKD,
'Dhamrai_CBU#RFD_CBU' Dhamrai_CBU#RFD_CBU,
'Dhamrai_CKD#DO_ISSUED' Dhamrai_CKD#DO_ISSUED,
'Dhamrai_CKD#BOOKED_DAP' Dhamrai_CKD#BOOKED_DAP,
'Dhamrai_CKD#DEALER_POINT_DISPLAY' Dhamrai_CKD#DEALER_POINT_DISPLAY,
'Dhamrai_CKD#FAIR_AND_DEMO' Dhamrai_CKD#FAIR_AND_DEMO,
'Dhamrai_CKD#OUTSIDE_BODY_WORKSHOP' Dhamrai_CKD#OUTSIDE_BODY_WORKSHOP,
'Dhamrai_CKD#BUS_BODY' Dhamrai_CKD#BUS_BODY,
'Dhamrai_CBU#PDI_PTS' Dhamrai_CBU#PDI_PTS,
'Dhamrai_CKD#TOTAL_OT' Dhamrai_CKD#TOTAL_OT,
'Joydebpur#RFD' Joydebpur#RFD,
'Joydebpur#DO_ISSUED' Joydebpur#DO_ISSUED,
'Joydebpur#BOOKED' Joydebpur#BOOKED,
'Joydebpur#TOTAL_OT' Joydebpur#TOTAL_OT,
'Joydebpur#FAIR_AND_DEMO' Joydebpur#FAIR_AND_DEMO,
'Joydebpur#PDI_PTS' Joydebpur#PDI_PTS,
'Joydebpur#DEALER_POINT_DISPLAY' Joydebpur#DEALER_POINT_DISPLAY,
'Joydebpur#OUTSIDE_BODY_WORKSHOP' Joydebpur#OUTSIDE_BODY_WORKSHOP,
'Cumilla#RFD' Cumilla#RFD,
'Cumilla#DO_ISSUED' Cumilla#DO_ISSUED,
'Cumilla#BOOKED' Cumilla#BOOKED,
'Cumilla#FAIR_AND_DEMO' Cumilla#FAIR_AND_DEMO,
'Bogra#DEALER_POINT_DISPLAY' Bogra#DEALER_POINT_DISPLAY,
'Cumilla#OUTSIDE_BODY_WORKSHOP' Cumilla#OUTSIDE_BODY_WORKSHOP,
'Cumilla#PDI_PTS' Cumilla#PDI_PTS,
'Cumilla#OUTSIDE_SERVICE_CENTER' Cumilla#OUTSIDE_SERVICE_CENTER,
'Chattogram#RFD' Chattogram#RFD,
'Chattogram#DO_ISSUED' Chattogram#DO_ISSUED,
'Chattogram#BOOKED' Chattogram#BOOKED,
'Chattogram#FAIR_AND_DEMO' Chattogram#FAIR_AND_DEMO,
'Chattogram#PDI_PTS' Chattogram#PDI_PTS,
'Chattogram#DEALER_POINT_DISPLAY' Chattogram#DEALER_POINT_DISPLAY,
'Chattogram#TOTAL_OT' Chattogram#TOTAL_OT,
'Jashore#RFD' Jashore#RFD,
'Jashore#DO_ISSUED' Jashore#DO_ISSUED,
'Jashore#BOOKED' Jashore#BOOKED,
'Jashore#PDI_PTS' Jashore#PDI_PTS,
'Jashore#FAIR_AND_DEMO' Jashore#FAIR_AND_DEMO,
'Jashore#DEALER_POINT_DISPLAY' Jashore#DEALER_POINT_DISPLAY,
'Jashore#OUTSIDE_BODY_WORKSHOP' Jashore#OUTSIDE_BODY_WORKSHOP,
'Jashore#TOTAL_OT' Jashore#TOTAL_OT,
'Bogra#RFD' Bogra#RFD,
'Bogra#DO_ISSUED' Bogra#DO_ISSUED,
'Bogra#BOOKED' Bogra#BOOKED,
'Bogra#FAIR_AND_DEMO' Bogra#FAIR_AND_DEMO,
'Bogra#OUTSIDE_BODY_WORKSHOP' Bogra#OUTSIDE_BODY_WORKSHOP,
'Bogra#PDI_PTS' Bogra#PDI_PTS,
'Bogra#TOTAL_OT' Bogra#TOTAL_OT,
'Dhamrai_CKD#PDI_PTS' Dhamrai_CKD#PDI_PTS,
'Dhamrai_CBU#DO_ISSUED' Dhamrai_CBU#DO_ISSUED,
'Dhamrai_CBU#BOOKED_DAP' Dhamrai_CBU#BOOKED_DAP                                           
))
GROUP BY PART_NO,PRODUCT_FAMILY, PARTDES


select * from IAL_STOCK_LOCATION_TEMP;