SELECT ROW_ID, ORDER_NO, CUSTOMER_NO, CUSTOMER_NAME, PRESENT_CITY, 
        FINANCIAL_INST, C_CUSTOMER_NO, C_CUSTOMER_NAME, C_PRESENT_CITY, RO_CODE, 
        RO_NAME, ZONE_NAME, REGNO, CATALOG_NO, CATALOG_DESC, STATUS, 
        LA_STATUS, NOVEHICLE, AUTHORIZE_CODE, FROM_DATE, 
        OPEN_AMOUNT, CREATE_DATE, LEASING_DATE , FSTINSAL_DATE, EMI_AMOUNT, 
        TOTALDUE, INTOTALDUE, INTRESTAMT, DP_AMOUNT, DP_OPEN, DELIVERY_DATE, SELLPRICE, 
        MR_COLL, MONTHLY_COLL, LAST_INSTAL_DATE, DP_PENALTY, DP_PARTIAL_PENALTY, INSTAL_PENALTY, 
        INSTAL_PARTIAL_PENALTY, DCDC_PENALTY, OVERDUE, OP_TAR_INST_AMT, TAR_INST_AMT, 
        CASE WHEN MONTHLY_COLL >= OP_TAR_INST_AMT THEN OP_TAR_INST_AMT
                     ELSE MONTHLY_COLL END INST_COLL
        
        FROM

        (SELECT ROW_ID, ORDER_NO, CUSTOMER_NO, CUSTOMER_NAME, PRESENT_CITY, 
                FINANCIAL_INST, C_CUSTOMER_NO, C_CUSTOMER_NAME, C_PRESENT_CITY, RO_CODE, 
                RO_NAME, ZONE_NAME, REGNO, CATALOG_NO, CATALOG_DESC, STATUS, 
                LA_STATUS, NOVEHICLE, AUTHORIZE_CODE, FROM_DATE, 
                OPEN_AMOUNT, CREATE_DATE, LEASING_DATE , FSTINSAL_DATE, EMI_AMOUNT, 
                TOTALDUE, INTOTALDUE, INTRESTAMT, DP_AMOUNT, DP_OPEN, DELIVERY_DATE, SELLPRICE, 
                MR_COLL, MONTHLY_COLL, LAST_INSTAL_DATE, DP_PENALTY, DP_PARTIAL_PENALTY, INSTAL_PENALTY, 
                INSTAL_PARTIAL_PENALTY, DCDC_PENALTY, LAST_MONTH_MR_COLL, OP_RECEIVABLE_BAL, OVERDUE, ACTUAL_OD,
                CL_RECEIVABLE, 
                CASE WHEN OP_RECEIVABLE_BAL >= EMI_AMOUNT THEN EMI_AMOUNT
                             ELSE OP_RECEIVABLE_BAL END OP_TAR_INST_AMT,
                CASE WHEN EMI_AMOUNT >= CL_RECEIVABLE THEN CL_RECEIVABLE
                             ELSE EMI_AMOUNT END TAR_INST_AMT
                FROM
                    (
                        SELECT CUS.ROW_ID, CUS.ORDER_NO, CUS.CUSTOMER_NO, CUS.CUSTOMER_NAME, CUS.PRESENT_CITY, 
                        CUS.FINANCIAL_INST, CUS.C_CUSTOMER_NO, CUS.C_CUSTOMER_NAME, CUS.C_PRESENT_CITY, CUS.RO_CODE, 
                        CUS.RO_NAME, CUS.ZONE_NAME, CUS.REGNO, CUS.CATALOG_NO, CUS.CATALOG_DESC, CUS.STATUS, 
                        CUS.LA_STATUS, CUS.NOVEHICLE, CUS.AUTHORIZE_CODE, 
                        CUS.LEASING_DATE , COLL.FSTINSAL_DATE, COLL.EMI_AMOUNT, 
                        COLL.TOTALDUE, COLL.INTOTALDUE, COLL.INTRESTAMT, COLL.DP_AMOUNT, COLL.DP_OPEN, COLL.DELIVERY_DATE, COLL.SELLPRICE, 
                        COLL.MR_COLL, COLL.MONTHLY_COLL, COLL.LAST_INSTAL_DATE, COLL.DP_PENALTY, COLL.DP_PARTIAL_PENALTY, COLL.INSTAL_PENALTY, 
                        COLL.INSTAL_PARTIAL_PENALTY, COLL.DCDC_PENALTY, COLL.FROM_DATE, COLL.TO_DATE, COLL.OPEN_AMOUNT, COLL.CREATE_DATE, 
                        --COLL.LEASING_DATE,
                        (MR_COLL - MONTHLY_COLL) LAST_MONTH_MR_COLL, 
                        CASE WHEN INTOTALDUE < (MR_COLL - MONTHLY_COLL) 
                        THEN 0 ELSE (INTOTALDUE - (MR_COLL - MONTHLY_COLL)) END OP_RECEIVABLE_BAL,
                        (TOTALDUE - MR_COLL) OVERDUE,
                        CASE WHEN TOTALDUE < MR_COLL THEN 0
                        ELSE (TOTALDUE - MR_COLL) END ACTUAL_OD,
                        CASE WHEN INTOTALDUE < MR_COLL THEN 0
                        ELSE (INTOTALDUE - MR_COLL) END CL_RECEIVABLE
                        FROM IAL_C_CO_COLLECTION_DETAIL COLL LEFT JOIN  IAL_C_COWISE_CUSTOMER_INFO CUS
                        ON COLL.ORDER_NO = CUS.ORDER_NO AND COLL.FROM_DATE = CUS.FROM_DATE
                        where COLL.FROM_DATE=TO_DATE('1-6-2022','dd-mm-yyyy')
                    ))
            
            
            ;

