using System.Data;
using System.Data.OracleClient;

namespace IALDashboard.DAL
{
    public class Stock_DAL : BaseDataAccessLayer
    {

        public DataTable DailyStockReport()
        {

            DataTable dt = new DataTable("Grid");

            try
            {

                OracleCommand com = GetSPCommand("SP_Daily_Stock_Report");
                com.Parameters.Add("P_PART_NO", OracleType.VarChar).Value = "";
                com.Parameters.Add("P_CONTRACT", OracleType.VarChar).Value = "";
                com.Parameters.Add("P_RECORDSET", OracleType.Cursor).Direction = ParameterDirection.Output;
                OracleDataAdapter oraData = new OracleDataAdapter(com);

                oraData.Fill(dt);
            }
            catch
            {

            }
            finally
            {
                Dispose();
            }

            return dt;


        }

        public DataTable StockTableTemp()
        {

            DataTable stocklist = new DataTable("StockReport");



            try
            {


                string StrSql = " SELECT "
                + " PARTDES, PART_NO, PRODUCT_FAMILY, "
                + " NVL(BUS_BODY_QTY,0) BUS_BODY_QTY, NVL(DEALER_PD_QTY,0) DEALER_PD_QTY, NVL(FAIR_DEMO_QTY,0) FAIR_DEMO_QTY,"
                + " NVL(LC_QTY,0) LC_QTY, NVL(OUTSIDE_BWS_QTY,0) OUTSIDE_BWS_QTY, NVL(TOTAL_OT_QTY,0) TOTAL_OT_QTY, "
                + " NVL(TRANSPORTT_QTY,0) TRANSPORTT_QTY, NVL(DHAMRAI_CKD#RFD_CKD,0) DHAMRAI_CKD#RFD_CKD ,NVL(DHAMRAI_CBU#RFD_CBU,0) DHAMRAI_CBU#RFD_CBU, "
                + " NVL(DHAMRAI_CKD#DO_ISSUED,0) DHAMRAI_CKD#DO_ISSUED, NVL(DHAMRAI_CKD#BOOKED_DAP,0) DHAMRAI_CKD#BOOKED_DAP ,NVL(DHAMRAI_CKD#DPD,0) DHAMRAI_CKD#DPD, "
                + " NVL(DHAMRAI_CKD#FAIR_AND_DEMO,0) DHAMRAI_CKD#FAIR_AND_DEMO, NVL(DHAMRAI_CKD#OBW,0) DHAMRAI_CKD#OBW,NVL(DHAMRAI_CKD#BUS_BODY,0) DHAMRAI_CKD#BUS_BODY, "
                + " NVL(DHAMRAI_CBU#PDI_PTS,0) DHAMRAI_CBU#PDI_PTS, NVL(DHAMRAI_CKD#TOTAL_OT,0) DHAMRAI_CKD#TOTAL_OT, NVL(JOYDEBPUR#RFD,0) JOYDEBPUR#RFD,"
                + " NVL(JOYDEBPUR#DO_ISSUED,0) JOYDEBPUR#DO_ISSUED, NVL(JOYDEBPUR#BOOKED,0) JOYDEBPUR#BOOKED, NVL(JOYDEBPUR#TOTAL_OT,0) JOYDEBPUR#TOTAL_OT,"
                + " NVL(JOYDEBPUR#FAIR_AND_DEMO,0) JOYDEBPUR#FAIR_AND_DEMO, NVL(JOYDEBPUR#PDI_PTS,0) JOYDEBPUR#PDI_PTS, NVL(JOYDEBPUR#DPD,0) JOYDEBPUR#DPD, "
                + " NVL(JOYDEBPUR#OBW,0) JOYDEBPUR#OBW, NVL(CUMILLA#RFD,0) CUMILLA#RFD, NVL(CUMILLA#DO_ISSUED,0) CUMILLA#DO_ISSUED, "
                + " NVL(CUMILLA#BOOKED,0) CUMILLA#BOOKED, NVL(CUMILLA#FAIR_AND_DEMO,0) CUMILLA#FAIR_AND_DEMO, NVL(BOGRA#DPD,0) BOGRA#DPD, "
                + " NVL(CUMILLA#OBW,0) CUMILLA#OBW, NVL(CUMILLA#PDI_PTS,0) CUMILLA#PDI_PTS, NVL(CUMILLA#OSC,0) CUMILLA#OSC, "
                + " NVL(CTG#RFD,0) CTG#RFD, NVL(CTG#DO_ISSUED,0) CTG#DO_ISSUED, NVL(CTG#BOOKED,0) CTG#BOOKED, "
                + " NVL(CTG#FAIR_AND_DEMO,0) CTG#FAIR_AND_DEMO, NVL(CTG#PDI_PTS,0) CTG#PDI_PTS, NVL(CTG#DPD,0) CTG#DPD, "
                + " NVL(CTG#TOTAL_OT,0) CTG#TOTAL_OT, NVL(JASHORE#RFD,0) JASHORE#RFD, NVL(JASHORE#DO_ISSUED,0) JASHORE#DO_ISSUED, "
                + " NVL(JASHORE#BOOKED,0) JASHORE#BOOKED, NVL(JASHORE#PDI_PTS,0) JASHORE#PDI_PTS, NVL(JASHORE#FAIR_AND_DEMO,0) JASHORE#FAIR_AND_DEMO, "
                + " NVL(JASHORE#DPD,0) JASHORE#DPD, NVL(JASHORE#OBW,0) JASHORE#OBW, NVL(JASHORE#TOTAL_OT,0) JASHORE#TOTAL_OT, "
                + " NVL(BOGRA#RFD,0) BOGRA#RFD, NVL(BOGRA#DO_ISSUED,0) BOGRA#DO_ISSUED, NVL(BOGRA#BOOKED,0) BOGRA#BOOKED, "
                + " NVL(BOGRA#FAIR_AND_DEMO,0) BOGRA#FAIR_AND_DEMO, NVL(BOGRA#OBW,0) BOGRA#OBW, NVL(BOGRA#PDI_PTS,0) BOGRA#PDI_PTS, "
                + " NVL(BOGRA#TOTAL_OT,0) BOGRA#TOTAL_OT,NVL(DHAMRAI_CKD#PDI_PTS,0) DHAMRAI_CKD#PDI_PTS, NVL(DHAMRAI_CBU#DO_ISSUED,0) DHAMRAI_CBU#DO_ISSUED, "
                + " NVL(DHAMRAI_CBU#BOOKED_DAP,0) DHAMRAI_CBU#BOOKED_DAP, "
                + " (COALESCE(DHAMRAI_CBU#PDI_PTS ,0) + COALESCE(JOYDEBPUR#PDI_PTS ,0) + COALESCE(CUMILLA#PDI_PTS ,0) + COALESCE(CTG#PDI_PTS ,0) + COALESCE(JASHORE#PDI_PTS ,0) + COALESCE(BOGRA#PDI_PTS ,0) + COALESCE(DHAMRAI_CKD#PDI_PTS ,0)) AS PDI_PTS, "
                + " (COALESCE(DHAMRAI_CKD#BOOKED_DAP ,0) + COALESCE(JOYDEBPUR#BOOKED ,0) + COALESCE(CUMILLA#BOOKED ,0) + COALESCE(CTG#BOOKED ,0) + COALESCE(JASHORE#BOOKED ,0) + COALESCE(BOGRA#BOOKED ,0) + COALESCE(DHAMRAI_CBU#BOOKED_DAP ,0)) AS BOOKED, "
                + " (COALESCE(DHAMRAI_CKD#DO_ISSUED, 0) + COALESCE(JOYDEBPUR#DO_ISSUED, 0) + COALESCE(CUMILLA#DO_ISSUED, 0) + COALESCE(CTG#DO_ISSUED, 0) + COALESCE(JASHORE#DO_ISSUED, 0) + COALESCE(BOGRA#DO_ISSUED, 0) + COALESCE(DHAMRAI_CBU#DO_ISSUED, 0)) AS DO_ISSUED, "
                + " (COALESCE(DHAMRAI_CKD#RFD_CKD, 0) + COALESCE(DHAMRAI_CBU#RFD_CBU,0) + COALESCE(JOYDEBPUR#RFD, 0) + COALESCE(CUMILLA#RFD, 0) + COALESCE(CTG#RFD, 0) + COALESCE(JASHORE#RFD,0) + COALESCE(BOGRA#RFD,0)) AS RFD, "
                + " (COALESCE(DHAMRAI_CBU#PDI_PTS ,0) + COALESCE(JOYDEBPUR#PDI_PTS ,0) + COALESCE(CUMILLA#PDI_PTS ,0) + COALESCE(CTG#PDI_PTS ,0) + COALESCE(JASHORE#PDI_PTS ,0) + COALESCE(BOGRA#PDI_PTS ,0) + COALESCE(DHAMRAI_CKD#PDI_PTS ,0) +"
                + " COALESCE(DHAMRAI_CKD#BOOKED_DAP ,0) + COALESCE(JOYDEBPUR#BOOKED ,0) + COALESCE(CUMILLA#BOOKED ,0) + COALESCE(CTG#BOOKED ,0) + COALESCE(JASHORE#BOOKED ,0) + COALESCE(BOGRA#BOOKED ,0) + COALESCE(DHAMRAI_CBU#BOOKED_DAP ,0) +"
                + " COALESCE(DHAMRAI_CKD#DO_ISSUED, 0) + COALESCE(JOYDEBPUR#DO_ISSUED, 0) + COALESCE(CUMILLA#DO_ISSUED, 0) + COALESCE(CTG#DO_ISSUED, 0) + COALESCE(JASHORE#DO_ISSUED, 0) + COALESCE(BOGRA#DO_ISSUED, 0) + COALESCE(DHAMRAI_CBU#DO_ISSUED, 0) +"
                + " COALESCE(DHAMRAI_CKD#RFD_CKD, 0) + COALESCE(DHAMRAI_CBU#RFD_CBU,0) + COALESCE(JOYDEBPUR#RFD, 0) + COALESCE(CUMILLA#RFD, 0) + COALESCE(CTG#RFD, 0) + COALESCE(JASHORE#RFD,0) + COALESCE(BOGRA#RFD,0)) AS TOTAL_QTY"
                + " FROM REPORTDB.IAL_STOCK_LOCATION_TEMP";




                //string StrSql = " SELECT * FROM  IAL_STOCK_LOCATION_TEMP";
                OracleCommand command = GetSQLCommand(StrSql);
                OracleDataAdapter odaAdapter = new OracleDataAdapter(command);
                odaAdapter.Fill(stocklist);
            }

            catch
            {
            }

            finally
            {
                Dispose();
            }

            return stocklist;
        }

    }
}

